### ISSUE TITLE
Not able to achieve the acceleration result in the paper

### ISSUE THREAD

**Issue by xiaodaxia** [forresti/libHOG#1]
Hello,
       I run the libHOG_cli with the use_voc5 = 0 or use_voc5 = 1,which I think is the switch to use acceleration and no accelration. According to the result in the paper, I shoud observe a 10-20 times speed up. But here is the result on my computer:
./libHOG_cli(use_voc=0)
  avg time for multiscale = 136.017822 ms 
    img pyramid: 57.502930 ms, malloc: 21.510010 ms, gradients: 14.038086 ms, hist: 25.382812 ms, norm: 16.210938 ms
    img pyramid: 4116650 pixels = 0.012350 GB, hist output: 0.010656 GB 
    img pyramid: 0.214771 GB/s, gradients: 0.879746 GB/s, hist: 0.486548 GB/s, norm: 0.657356 GB/s 

 avg time for multiscale = 226.262207 ms (use_voc=1)
    img pyramid: 42.583984 ms, malloc: 19.838867 ms, gradients: 104.439209 ms, hist: 44.923828 ms, norm: 12.847900 ms
    img pyramid: 4116650 pixels = 0.012350 GB, hist output: 0.010656 GB 
    img pyramid: 0.290014 GB/s, gradients: 0.118250 GB/s, hist: 0.274909 GB/s, norm: 0.829424 GB/s 

So the running time is 226ms vs 136ms. I do not know I missed which step. 
My environment is Ubuntu 17.04, opencv2.4.13, cpu is 4 core i5-4200U.

**Comment by forresti** [comment]
Hmm... This doesn't surprise me too much. Here is my hypothesis:
- The vectorization is working properly
- The multithreading isn't helping much because the 4200U is just a 2-core processor

The `gradients` is the function that we vectorized the most aggressively, and it looks like you're getting a 7.4x speedup (out of a best-case 8x for 8-wide vectors) for `gradients`. The other functions we focused more on improving memory access pattern and multicore parallelism. But, again, with 2 cores, you don't have that much opportunity for multicore parallelism. 

My suggestion: get a processor with more cores. :)
